export default function Footer() {
  return (
    <footer className="border-t border-line/60 py-8">
      <div className="mx-auto flex max-w-6xl flex-col items-center gap-2 px-6 text-center">
        <p className="font-mono text-[10px] uppercase tracking-[0.2em] text-paper/30">
          NeuroScan · Research prototype · Not for clinical use
        </p>
        <p className="max-w-md text-[11px] leading-relaxed text-paper/25">
          Predictions are generated by a convolutional neural network for
          educational purposes only. Always consult a qualified radiologist
          for an actual diagnosis.
        </p>
      </div>
    </footer>
  )
}
